pipeline {
    agent any

    stages {
        stage('Declarative: Checkout SCM') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'javac JenkinsBSP/src/Calculator.java'
            }
        }
        stage('Test') {
            steps {
                sh 'env JAVA_HOME=/usr/lib/jvm/java-8-openjdk-amd64 /usr/lib/jvm/java-8-openjdk-amd64/bin/java JenkinsBSP/src/CalculatorTest'
            }
        }
    }
}
