pipeline {
    agent any

    environment {
        INPUT_VALUE_1 = '5'
        INPUT_VALUE_2 = '10'
        OPERATOR = '+'
    }

    stages {
        stage('Declarative: Checkout SCM') {
            steps {
                checkout scm
            }
        }
        stage('Build') {
            steps {
                sh 'javac JenkinsBSP/src/Calculator.java'
            }
        }
        stage('Test') {
            steps {
                sh "echo ${env.INPUT_VALUE_1} >> input.txt"
                sh "echo ${env.INPUT_VALUE_2} >> input.txt"
                sh "echo ${env.OPERATOR} >> input.txt"
                sh "ls"
                sh "ls JenkinsBSP/src"
                sh "cat JenkinsBSP/src/Calculator.class"
                sh "java JenkinsBSP/src/Calculator < input.txt > output.txt"
                sh "cat output.txt"
            }
        }
    }
}
